### ISSUE TITLE
limit response

### ISSUE THREAD

**Issue by rahulsya** [tomorisakura/unofficial-masakapahariini-api#1]
can you add feature, limit response when get items

**Comment by tomorisakura** [comment]
did you mean a limit response to limit result the data right ? example response only fetch a 3 or more right ?

**Comment by tomorisakura** [comment]
> can you add feature, limit response when get items

i'm already added that features so here you go bro https://github.com/tomorisakura/unofficial-masakapahariini-api#endpoint-usage

**Comment by rahulsya** [comment]
really big thanks, for the update 👍 😄
