### ISSUE TITLE
Permisi, repo ini masih bisa digunakan?

### ISSUE THREAD

**Issue by Faizaliso** [tomorisakura/unofficial-masakapahariini-api#15]
ini pesan di browser saya 

This Serverless Function has crashed.

Your connection is working correctly.

Vercel is working correctly.

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: sin1::pb4l4-1669100779873-9284391a12e6

If you are a visitor, contact the website owner or try again later.
If you are the owner, [learn how to fix the error](https://vercel.com/docs/error/application/FUNCTION_INVOCATION_FAILED) and [check the logs](https://masak-apa-tomorisakura.vercel.app/_logs).

**Comment by tomorisakura** [comment]
masih bisa, kadang kena 500 tapi kembali normal lagi
