### ISSUE TITLE
search-recipes 502: BAD_GATEWAY

### ISSUE THREAD

**Issue by frhnmubarok** [tomorisakura/unofficial-masakapahariini-api#2]
Ketika mengakses endpoint `search-recipes` sering mendapat response 502: BAD_GATEWAY

**Comment by tomorisakura** [comment]
> Ketika mengakses endpoint `search-recipes` sering mendapat response 502: BAD_GATEWAY

query nya seperti apa ya mas yang di search ? klo punya saya jarang mendapatkan err itu 
dan saya coba hit tidak terjadi err mas

![2020-12-17](https://user-images.githubusercontent.com/23102910/102474491-49ef8d80-408b-11eb-9519-b0fba36e427f.jpg)

**Comment by frhnmubarok** [comment]
![ss1](https://user-images.githubusercontent.com/75704041/102485116-bf625a80-4099-11eb-9cdf-2ffcb4f6c528.PNG)
contoh query nya itu

![ss2](https://user-images.githubusercontent.com/75704041/102485156-cd17e000-4099-11eb-98f0-f1d886fbf202.PNG)

**Comment by tomorisakura** [comment]
> ![ss1](https://user-images.githubusercontent.com/75704041/102485116-bf625a80-4099-11eb-9cdf-2ffcb4f6c528.PNG)
> contoh query nya itu
> 
> ![ss2](https://user-images.githubusercontent.com/75704041/102485156-cd17e000-4099-11eb-98f0-f1d886fbf202.PNG)

saran saya, klo mau testing menggunakan postman mas, klo hit di browser pastikan query tidak ada spasi contohnya `nasi goreng` = `nasi%20goreng` 

jadi url nya seperti ini : https://masak-apa.tomorisakura.vercel.app/api/search/?q=nasi%20goreng

ini result yang diterima melalui postman 
![tomo_nasi_goreng](https://user-images.githubusercontent.com/23102910/102485919-d5244f80-409a-11eb-866c-e3d735797a78.PNG)

**Comment by frhnmubarok** [comment]
> 
> 
> > ![ss1](https://user-images.githubusercontent.com/75704041/102485116-bf625a80-4099-11eb-9cdf-2ffcb4f6c528.PNG)
> > contoh query nya itu
> > ![ss2](https://user-images.githubusercontent.com/75704041/102485156-cd17e000-4099-11eb-98f0-f1d886fbf202.PNG)
> 
> saran saya, klo mau testing menggunakan postman mas, klo hit di browser pastikan query tidak ada spasi contohnya `nasi goreng` = `nasi%20goreng`
> 
> jadi url nya seperti ini : https://masak-apa.tomorisakura.vercel.app/api/search/?q=nasi%20goreng
> 
> ini result yang diterima melalui postman
> ![tomo_nasi_goreng](https://user-images.githubusercontent.com/23102910/102485919-d5244f80-409a-11eb-866c-e3d735797a78.PNG)

![ss3](https://user-images.githubusercontent.com/75704041/102489574-3bf83780-40a0-11eb-9eb1-e40133738fea.PNG)
coba hit beberapa kali mas. ini response di postman saya

**Comment by tomorisakura** [comment]
> > > ![ss1](https://user-images.githubusercontent.com/75704041/102485116-bf625a80-4099-11eb-9cdf-2ffcb4f6c528.PNG)
> > > contoh query nya itu
> > > ![ss2](https://user-images.githubusercontent.com/75704041/102485156-cd17e000-4099-11eb-98f0-f1d886fbf202.PNG)
> > 
> > 
> > saran saya, klo mau testing menggunakan postman mas, klo hit di browser pastikan query tidak ada spasi contohnya `nasi goreng` = `nasi%20goreng`
> > jadi url nya seperti ini : https://masak-apa.tomorisakura.vercel.app/api/search/?q=nasi%20goreng
> > ini result yang diterima melalui postman
> > ![tomo_nasi_goreng](https://user-images.githubusercontent.com/23102910/102485919-d5244f80-409a-11eb-866c-e3d735797a78.PNG)
> 
> ![ss3](https://user-images.githubusercontent.com/75704041/102489574-3bf83780-40a0-11eb-9eb1-e40133738fea.PNG)
> coba hit beberapa kali mas. ini response di postman saya

kalau spam req seperti itu saya rasa ada dibagian vercelnya, lagian mas mau bikin apa ya kok requestnya harus spam seperti itu ? 😀

**Comment by frhnmubarok** [comment]
> 
> 
> > > > ![ss1](https://user-images.githubusercontent.com/75704041/102485116-bf625a80-4099-11eb-9cdf-2ffcb4f6c528.PNG)
> > > > contoh query nya itu
> > > > ![ss2](https://user-images.githubusercontent.com/75704041/102485156-cd17e000-4099-11eb-98f0-f1d886fbf202.PNG)
> > > 
> > > 
> > > saran saya, klo mau testing menggunakan postman mas, klo hit di browser pastikan query tidak ada spasi contohnya `nasi goreng` = `nasi%20goreng`
> > > jadi url nya seperti ini : https://masak-apa.tomorisakura.vercel.app/api/search/?q=nasi%20goreng
> > > ini result yang diterima melalui postman
> > > ![tomo_nasi_goreng](https://user-images.githubusercontent.com/23102910/102485919-d5244f80-409a-11eb-866c-e3d735797a78.PNG)
> > 
> > 
> > ![ss3](https://user-images.githubusercontent.com/75704041/102489574-3bf83780-40a0-11eb-9eb1-e40133738fea.PNG)
> > coba hit beberapa kali mas. ini response di postman saya
> 
> kalau spam req seperti itu saya rasa ada dibagian vercelnya, lagian mas mau bikin apa ya kok requestnya harus spam seperti itu ? 😀

bukan spam sih, cuma kalo hit pertama response nya 502 otomatis saya req terus. itu termasuk spam ?
kalo dari vercelnya berarti solved ya
