### ISSUE TITLE
search-recipes 502: BAD_GATEWAY

### ISSUE THREAD

**Issue by herihermwn** [tomorisakura/unofficial-masakapahariini-api#3]
Ketika mengakses endpoint search-recipes mendapat response 502: BAD_GATEWAY, sudah saya coba di postman dan aplikasi android dari repo https://github.com/tomorisakura/masak-apa. Kemarin sempat coba normal saja, tapi malam ini entah kenapa error.

**Comment by tomorisakura** [comment]
> Ketika mengakses endpoint search-recipes mendapat response 502: BAD_GATEWAY, sudah saya coba di postman dan aplikasi android dari repo https://github.com/tomorisakura/masak-apa. Kemarin sempat coba normal saja, tapi malam ini entah kenapa error.

Saat ini website induknya mengalami trouble mas, sehingga pada saat search mengalami 502
![Screenshot_20210130-031046](https://user-images.githubusercontent.com/23102910/106322965-36019300-62a9-11eb-9c95-b97bdab94ac8.jpg)

**Comment by herihermwn** [comment]
> > Ketika mengakses endpoint search-recipes mendapat response 502: BAD_GATEWAY, sudah saya coba di postman dan aplikasi android dari repo https://github.com/tomorisakura/masak-apa. Kemarin sempat coba normal saja, tapi malam ini entah kenapa error.
> 
> Saat ini website induknya mengalami trouble mas, sehingga pada saat search mengalami 502
> ![Screenshot_20210130-031046](https://user-images.githubusercontent.com/23102910/106322965-36019300-62a9-11eb-9c95-b97bdab94ac8.jpg)

Ohh oke, Terima kasih ya
