### ISSUE TITLE
Masalah dengan CORS policy

### ISSUE THREAD

**Issue by oktavianoandy** [tomorisakura/unofficial-masakapahariini-api#4]
Permisi kak. Saya Menggunakan API ini di React JS. Ketika datanya saya fetch dan saya baca di console, ada eror CORS Policy. Untuk masalah tersebut bagaimana solusinya kak? Terimakasih.
Berikut ini erornya : 
![image](https://user-images.githubusercontent.com/52455416/120222824-c4dbe780-c26a-11eb-9a9b-1dd779f309db.png)

**Comment by tomorisakura** [comment]
udah coba pake ini mas ? https://reactjs.org/docs/cross-origin-errors.html

**Comment by oktavianoandy** [comment]
Siap mas, nanti saya coba. Terimakasih banyak ya mas. 🙇‍♂️🙇‍♂️
