### ISSUE TITLE
Webpack CORS Issue

### ISSUE THREAD

**Issue by Aqshola** [tomorisakura/unofficial-masakapahariini-api#5]
Terkena Error CORS pada saat fetch
![image](https://user-images.githubusercontent.com/52363719/131346614-510755f1-f124-48f5-a428-984940815b8d.png)

untuk konfigurasi fetchnya sudah menggunakan allow origin
![image](https://user-images.githubusercontent.com/52363719/131346789-148a370c-e931-420e-9522-9744114c7b0b.png)
![image](https://user-images.githubusercontent.com/52363719/131346834-4b134e04-37ae-40cf-af89-1ca2a97cc6cf.png)

**Comment by Aqshola** [comment]
solved dengan menambahkan proxy
![image](https://user-images.githubusercontent.com/52363719/131366154-e2c154ae-ecf6-4cea-a29d-25b48fc15a61.png)

**Comment by tomorisakura** [comment]
Nice, jika menggunakan native JS alangkah baiknya menggunakan proxy
